{% set name = "juliaup" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/JuliaLang/{{ name }}/archive/v{{ version }}.zip
  sha256: f8d8ed62b70307c9914655f056e6737b5b7b8d948bf3e4b8f7693c9203c8319c

build:
  script:
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
    - cargo install --locked --root "$PREFIX" --path .  # [unix]
    - cargo install --locked --root "%LIBRARY_PREFIX%" --path . || goto :error  # [win]
    - rm -f "${PREFIX}/.crates.toml"  # [unix]
    - del /F /Q "%LIBRARY_PREFIX%\.crates.toml"  # [win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - juliaup status

about:
  home: https://github.com/JuliaLang/juliaup
  summary: Julia installer and version multiplexer
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - mkitti
    - ngam
